service: kontova
image: bosseschumacher/kontova

servers:
  web:
    hosts:
      - 62.238.45.187

volumes:
  - /var/lib/kontova/storage:/rails/storage
  - /var/kontova-keys:/rails/config/keys

proxy:
  ssl: true
  hosts:
    - kontova.de
    - tuebingerwingolf.kontova.de
    - showcase.kontova.de

registry:
  username: bosseschumacher
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  secrets:
    - RAILS_MASTER_KEY

env:
  clear:
    RAILS_ENV: production
    APP_HOST: kontova.de
    SOLID_QUEUE_IN_PUMA: "true"
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - MAIL_USERNAME
    - MAIL_PASSWORD

accessories:
  postgres:
    image: postgres:17
    host: 62.238.45.187
    port: 5432
    env:
      clear:
        POSTGRES_DB: kontova_production
        POSTGRES_USER: kontova
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
